# Generated by Django 3.2.11 on 2022-09-08 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessUnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='LineNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='business_unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.businessunity'),
        ),
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('accident_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.accidenttype')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.area')),
                ('business_unity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.businessunity')),
                ('line_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.linenumber')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.turns')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
