# Generated by Django 3.2.11 on 2022-09-09 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accidents', '0002_auto_20220908_1754'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.area')),
                ('business_unity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.businessunity')),
                ('line_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.linenumber')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accidents.turns')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
